remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: Automatic Academic CV
description: An RMarkdown document and associated tooling to automatically generate a PDF or Word document with your publication data, extracted from Google Scholar profile
